#!/usr/bin/env bash

VERSION="0.1"

SCRIPT_HOME="$(cd "$(dirname "$0")" && pwd -P)"

LIBRARY_PATH="$SCRIPT_HOME/language/target/"
LANGUAGE_PATH="$SCRIPT_HOME/language/target/nock-language.jar"
LAUNCHER_PATH="$SCRIPT_HOME/launcher/target/serf-$VERSION-SNAPSHOT.jar"
MAIN_CLASS="net.frodwith.jaque.Serf"

#  -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n,quiet=y
java -Dgraal.LogFile=graal-log.txt -Dtruffle.class.path.append="$LANGUAGE_PATH" -Djava.library.path="$LIBRARY_PATH" -cp "$LAUNCHER_PATH" "$MAIN_CLASS" $@
